### ISSUE TITLE
Does this crate support win10: defaultlib 'LIBCMT' conflicts with use of other libs

### ISSUE THREAD

**Issue by fengqi2019** [angelcam/rust-ac-ffmpeg#16]
- I install ffmpeg via vcpkg。
- then set env. variables: 
> FFMPEG_INCLUDE_DIR=D:\git\vcpkg\packages\ffmpeg_x64-windows-static\include
> FFMPEG_LIB_DIR=D:\git\vcpkg\packages\ffmpeg_x64-windows-static\lib

- then run example, but could not compile: 
`
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.10u7igex2h6pxjd7.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.10xklarlvkhsetjy.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.13o85c09ghxyxh6b.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1dfz431yyydkeyfw.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1e7zpdhzhd9ioeve.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1fmjy7tvyiexjw7x.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1ml2vgmy0gccimw2.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1ns7s6b021ate121.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.1t8lpbus2g6ni72x.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.20ldbw01msivpdlt.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2iaulp23rdr3l0fu.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2iqijhy4aonebzl6.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2j1w9od163qghu28.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2l4d9iz9z8nbknub.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2mdt4wlkkx7wrfcd.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2mtof1vbjo7qlbsr.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2orjt1jejr15uvy4.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2wl5whkzfuhbsw4s.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.2z5h51f48l9g8p4w.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.31pdoidyhqhej59w.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.329e285e7opryg7s.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.33bjjbkrlyempvyr.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.382ec7dh31mjcaih.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.38v1hgvcxjpsfucl.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3cl8yqwkrunf5onj.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3gk308tbkzuye3ab.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3oiie7ciq4oqokmx.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3unh34ipj40hiix2.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3vvrv177aal4iwu0.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.3wbp7qqrrsx8xaok.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.41vr4kvh3fakpopl.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.44obcqi1j0cly6k1.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.489gswkzerbuldx6.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.49ac4qbg77ssz4ad.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4abs26i759mhlgmm.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4c0719v3g0e9ubfm.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4jpwbakj7k83jlo3.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4r47ulb7s4iaulmx.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4rcu4xgfdbj7ffsx.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4slhi4qrg6hluavf.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4x5d7pmazp5hb3lo.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.4ztnymn0e4oolytl.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.522atrttbnat8a2a.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.524boiybnxm663zn.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.55sm7o1zgraxit3f.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.56h5jfda8965tgmb.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.57fx8t38ibu79x4a.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.58gytnz0cqgbgsu.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.5bd7579r88j3d4xu.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.5g1xsn4jwj7n9dwd.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.dx561a81sy32q7g.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.f674xqkeju6m453.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.juu3vl7vl5dn6ef.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.k597tf42c7n9ntn.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.ktas9bdsupcbas6.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.n12ucx1dgg3ggl8.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.pwe57vkwzoz9mbx.rcgu.o" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.uximbsrx0r90kcu.rcgu.o" "/OUT:d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.exe" "d:\\IdeaProjects\\exp\\target\\debug\\deps\\exp.202qs0688s7usrbf.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:d:\\IdeaProjects\\exp\\target\\debug\\deps" "/LIBPATH:d:\\IdeaProjects\\exp\\target\\debug\\build\\ac-ffmpeg-9f0a833c16f9003e\\out" "/LIBPATH:D:\\git\\vcpkg\\packages\\ffmpeg_x64-windows-static\\lib" "/LIBPATH:C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libclap-8f4c667e756ec9de.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libvec_map-94ced0c0acfb5c21.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libtextwrap-6c6f27b10ba71a41.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libunicode_width-cf68dca962f2242c.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libstrsim-122152890de853b9.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libbitflags-82fb5b4d1ff6ce3a.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libatty-57b15f5d4123f291.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libwinapi-2376685cce1a5772.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\libac_ffmpeg-a9b60b4ddb1b97cc.rlib" "D:\\IdeaProjects\\exp\\target\\debug\\deps\\liblazy_static-d20113d2098b0e23.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-0087fff1d6c84113.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-e9a9adcb7b282f86.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-c17bc77d789f8359.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-1f739c53c46039b3.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-b12f9afb50af9e82.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-4813d8391ae0f1e1.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-a6dfd598b03abbd4.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-8e04de9ca6363561.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-05126e82a7fe403c.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-7f3e1ef8417012fa.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-df80c014103f27c5.rlib" "C:\\Users\\36225\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-f404d34c325d6d79.rlib" "advapi32.lib" "cfgmgr32.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "opengl32.lib" "user32.lib" "winspool.lib" "avcodec.lib" "avformat.lib" "avutil.lib" "swresample.lib" "swscale.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  
= note: LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
          avcodec.lib(mfenc.o) : error LNK2019: unresolved external symbol MFCreateMediaType referenced in function mf_choose_output_type
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_ICodecAPI
          avcodec.lib(mfenc.o) : error LNK2001: unresolved external symbol IID_IMFMediaEventGenerator
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoUninitialize referenced in function ff_free_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoInitializeEx referenced in function ff_instantiate_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol __imp_CoTaskMemFree referenced in function ff_instantiate_mf
          avcodec.lib(dxva2.o) : error LNK2001: unresolved external symbol __imp_CoTaskMemFree
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFStartup referenced in function ff_instantiate_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFShutdown referenced in function ff_free_mf
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFCreateAlignedMemoryBuffer referenced in function ff_create_memory_sample
          avcodec.lib(mf_utils.o) : error LNK2019: unresolved external symbol MFCreateSample referenced in function ff_create_memory_sample
          avcodec.lib(mf_utils.o) : error LNK2001: unresolved external symbol IID_IMFTransform
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol AcquireCredentialsHandleA referenced in function tls_open
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_FreeCredentialsHandle referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol InitializeSecurityContextA referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_DeleteSecurityContext referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol __imp_ApplyControlToken referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol QueryContextAttributesA referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol FreeContextBuffer referenced in function tls_close
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol EncryptMessage referenced in function tls_write
          avformat.lib(tls_schannel.o) : error LNK2019: unresolved external symbol DecryptMessage referenced in function tls_read
          avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptOpenAlgorithmProvider referenced in function av_get_random_seed
          avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptCloseAlgorithmProvider referenced in function av_get_random_seed
          avutil.lib(random_seed.o) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function av_get_random_seed
          d:\IdeaProjects\exp\target\debug\deps\exp.exe : fatal error LNK1120: 23 unresolved externals`

- so, something i shoud do?

**Comment by operutka** [comment]
I'm afraid I won't be of much help here. The crate haven't been tested on Windows. And I'm not a Windows developer, so I'm not exactly sure what the LIBCMT conflict means.

Anyway there seems to be quite a lot of missing symbols the linker is complaining about. Apparently vcpkg builds ffmpeg with some external dependencies that are not available to the linker. You have several options:

1. You can build your own version of ffmpeg without these dependencies.
2. You can try building your application with shared ffmpeg libs instead of the static versions. There is a chance that the linker will be able to find the shared dependencies in your system automatically.
3. You can modify the build script of ac-ffmpeg to use the [vcpkg](https://crates.io/crates/vcpkg) crate on windows. This crate should be able to pull in all extra dependencies automatically from the vcpkg package description.
4. You can try to install ffmpeg via MSYS but you'll also have to switch from msvc to gnu toolchain (available via MSYS as well).

If you manage to find out a working solution with vcpkg, feel free to open a pull request. A patch would be welcome.

**Comment by fengqi2019** [comment]
solve the problem:
1. set env:
FFMPEG_INCLUDE_DIR=D:\git\vcpkg\packages\ffmpeg_x64-windows-static\include
FFMPEG_LIB_DIR=D:\git\vcpkg\packages\ffmpeg_x64-windows-static\lib

2. add cargo config.new folder and file: .cargo/config.the context is:
`[target.x86_64-pc-windows-msvc]
#rustflags = ["-C", "link-arg=/STACK:4194304"]
rustflags = ["-C", "link-arg=Mfplat.lib", "-C", "link-arg=Strmiids.lib"
    ,"-C", "link-arg=Mfuuid.lib", "-C", "link-arg=Bcrypt.lib"
    ,"-C" , "link-arg=Secur32.lib"
    ,"-C" , "link-arg=Ole32.lib"
    ,"-C", "link-args=/NODEFAULTLIB:libcmt.lib"
]`

**Comment by operutka** [comment]
Good! I'll try to integrate the vcpkg lib in to the build script in the future to make things easier.
