### ISSUE TITLE
Allow setting stream metadata in Muxer

### ISSUE THREAD

**Issue by tnibler** [angelcam/rust-ac-ffmpeg#19]
At the moment it looks like it's not possible to set metadata on individual `AVStream`s from Rust. It would be nice to allow things like the following:

```
av_dict_set_int(&video_stream->metadata, "rotate", 90, 0);
```

I think it would make sense to allow setting metadata fields in `Muxer::add_stream`.

**Comment by operutka** [comment]
I'm keeping the issue open until it's released.

**Comment by operutka** [comment]
@tnibler Currently I'm waiting for PR #21 to be finished and merged. The PR will introduce a `Stream` type and it might be useful to refactor your changes and move the metadata method to the new stream type.

I'm not sure how long it will take and I don't want to block you in your development. If you'd like your changes to be released ASAP, I can release it this week and do the refactoring once the other PR is ready. If it isn't blocking you, I'd prefer to wait with the release.

**Comment by tnibler** [comment]
No worries, I can pin my dependency to the respective commit so there's no rush to release.

**Comment by operutka** [comment]
It's been released, so I think I can close this issue now.
