### ISSUE TITLE
Use of goto statements in C code

### ISSUE THREAD

**Issue by niklaskorz** [angelcam/rust-ac-ffmpeg#22]
While going through the C code, I was wondering whether there was any reason for the excessive and seemingly unnecessary use of goto statements.
For example:

```c
AVPacket* ffw_packet_new(int size) {
    AVPacket* packet = av_packet_alloc();
    if (packet == NULL) {
        return NULL;
    }

    if (av_new_packet(packet, size) != 0) {
        goto err;
    }

    return packet;

err:
    av_packet_free(&packet);

    return NULL;
}
```

Would be shorter and easier to understand in the goto-less variant:

```c
AVPacket* ffw_packet_new(int size) {
    AVPacket* packet = av_packet_alloc();
    if (packet == NULL) {
        return NULL;
    }

    if (av_new_packet(packet, size) != 0) {
        av_packet_free(&packet);
        return NULL;
    }

    return packet;
}
```

**Comment by operutka** [comment]
Using goto for error handling is quite common practice in C. It allows you to have a single place where you can handle all the necessary de-allocations. You're right that in this particular case it isn't really that necessary. But a habit is a habit :smile:

**Comment by niklaskorz** [comment]
I see, thanks for the quick response!

**Comment by operutka** [comment]
So I guess, I can close the issue :)
