### ISSUE TITLE
AAC to Opus transcoding. 

### ISSUE THREAD

**Issue by Lighty0410** [angelcam/rust-ac-ffmpeg#23]
Hey folks! I'm trying to transcode AAC file to Opus and then write it to a file. But currently facing an issue - i'm not able to play the file via vlc\ffplay\etc. 
For example that's the output from ffprobe - 

> [m4v @ 0x5630c0e255c0] Format m4v detected only with low score of 5, misdetection possible!
> [mpeg4 @ 0x5630c0e27340] time_increment_bits 0 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
> [mpeg4 @ 0x5630c0e27340] time_increment_bits set to 8 bits, based on bitstream analysis
> [mpeg4 @ 0x5630c0e27340] time_increment_bits 4 is invalid in relation to the current bitstream, this is likely caused by a missing VOL header
> [mpeg4 @ 0x5630c0e27340] time_increment_bits set to 8 bits, based on bitstream analysis
> [mpeg4 @ 0x5630c0e27340] looks like this file was encoded with (divx4/(old)xvid/opendivx) -> forcing low_delay flag
> [mpeg4 @ 0x5630c0e27340] Marker bit missing at 75 of 3684536 before width
> [mpeg4 @ 0x5630c0e27340] Marker bit missing at 89 of 3684536 before height
> [mpeg4 @ 0x5630c0e27340] N-bit not supported
> [mpeg4 @ 0x5630c0e27340] quant precision 4
> [mpeg4 @ 0x5630c0e27340] Invalid Complexity estimation method 3
> [mpeg4 @ 0x5630c0e27340] reduced resolution VOP not supported
> [mpeg4 @ 0x5630c0e27340] scalability not supported

What's interesting. All the same pipeline works completely fine for AAC->MP3 transcoding. 
Can you please tell what i'm doing wrong ? Thanks in advance! 
AAC -> MP3 transcoding - https://gist.github.com/Lighty0410/5c6bcf02aae5ac348736f32eda4da287
AAC -> OPUS transcoding. The only difference here is the sample format both for audio encoder\resampler and codec for AudioEncoder  - https://gist.github.com/Lighty0410/f01193891f51122f82324975742b3c29

**Comment by operutka** [comment]
Hi @Lighty0410!

I don't have a first-hand experience with Opus but based on the output from ffprobe, I think that you cannot simply put Opus encoded audio into a file (unlike MP3 which is an audio codec and also a file format). The ffprobe output indicates that ffprobe tried to interpret the file as m4v (i.e. MP4 video) and failed.

Personally, I'd try adding ".opus" at the end of the file name. It's possible that ffprobe/ffplay/vlc will then be able to guess the format based on the filename extension. If it doesn't help, you'll probably have to mux the encoded audio into one of the supported containers. Quick googling shows that Ogg, WebM, Matroska and MPEG-TS support Opus audio.

**Comment by Lighty0410** [comment]
@operutka Yeah, i tried to create a file with .opus extension. All the same result. Seems like i really need to put the data to a container indeed. 
Another interesting things: 
1) ffmpeg -i file.aac -c:a libopus opus_file.opus works fine and the audio plays fine with just .opus extension.
2) Even if i set the the file extension to .opus ffprobe still think it's mp4v.  
Thanks a lot for help!

**Comment by Lighty0410** [comment]
@operutka so, i tried using a muxer. And now there's another problem. The application just stuck. 
https://github.com/angelcam/rust-ac-ffmpeg/blob/7a7ff68a621a8b2e8810de88748b237180e0feaf/src/format/muxer.rs#L157 - here's the line where everything stops. 
Here's what i'm doing - https://gist.github.com/Lighty0410/e67e936410bb20b7d2dd780ba90777f6

**Comment by operutka** [comment]
@Lighty0410 the problem is here:
https://gist.github.com/Lighty0410/e67e936410bb20b7d2dd780ba90777f6#file-aac_opus-rs-L25

You're trying to create a muxer using a read stream (the ffmpeg can't write anything). I'm not sure why it doesn't end with an error, you'd probably have to dive into the ffmpeg code to find the exact reason. Anyway, you should create your muxer IO like this:
```rust
let io = IO::from_seekable_write_stream(output_file);
```

**Comment by Lighty0410** [comment]
@operutka Oh god.... That was insanely stupid by me. Just a typo...
I leave it here. Maybe it will be useful for someone in the future and google will se it - https://gist.github.com/Lighty0410/13104e7357b3121998caa6969110e818
Thank you a lot <3.
