### ISSUE TITLE
Output to DRM framebuffers

### ISSUE THREAD

**Issue by FallingSnow** [angelcam/rust-ac-ffmpeg#24]
Is it possible to specify the output buffers in this library? I'd like the decoder to write directly to DRM Prime output buffers.

**Comment by operutka** [comment]
No, this isn't possible right now and, to be honest, I don't know how I'd do it in the plain ffmpeg. If you have some experience with this topic, feel free to share a code snippet or open a pull request.

**Comment by FallingSnow** [comment]
I've seen some documentation on it but it seems a little tricky to setup. I decided to just use ffmpeg for the parsing and V4L2 for the actual decode which is fairly simple to output straight into DRM.
