### ISSUE TITLE
How to define packet size for muxer ? 

### ISSUE THREAD

**Issue by Lighty0410** [angelcam/rust-ac-ffmpeg#26]
Hey ! First of all, thank you a lot for this repo, it's simply awesome :). 
The question is. How can i set packet size for muxer ? 
Using the native library there's a field for AVFormatContext - unsigned int packet_size. But how can i set it here ? 
Since i'm using the muxer for an RTP output it requires a certain number of packets defined. 
Thanks in advance!

**Comment by operutka** [comment]
Hi! Thank you.

You can set any option that would be normally accepted by the ffmpeg app using the `MuxerBuilder::set_option()` and `Muxer::set_option()` methods. In your case, it'd be probably something like:
```rust
let mut builder = Muxer::builder()
    .set_option("packetsize", 1234);

...
```

In future versions, I'll add methods for listing available options.

**Comment by Lighty0410** [comment]
> Hi! Thank you.
> 
> You can set any option that would be normally accepted by the ffmpeg app using the `MuxerBuilder::set_option()` and `Muxer::set_option()` methods. In your case, it'd be probably something like:
> 
> ```rust
> let mut builder = Muxer::builder()
>     .set_option("packetsize", 1234);
> 
> ...
> ```
> 
> In future versions, I'll add methods for listing available options.

Wow. I tried using `pkt_size` before and it didn't help. But for some reasons `packetsize` works great. 
Thank you a lot ! 
Closing the issue :)

**Comment by operutka** [comment]
Yes. For some reason, FFmpeg devs decided to name this option differently than the struct field itself. Anyway, if you list all available ffmpeg options in command line, you'll find this:
```
$ ffmpeg -h full
...
  -packetsize        <int>        E......... set packet size (from 0 to INT_MAX) (default 0)
...
```

**Comment by Lighty0410** [comment]
> Yes. For some reason, FFmpeg devs decided to name this option differently than the struct field itself. Anyway, if you list all available ffmpeg options in command line, you'll find this:
> 
> ```
> $ ffmpeg -h full
> ...
>   -packetsize        <int>        E......... set packet size (from 0 to INT_MAX) (default 0)
> ...
> ```

Oh, thanks a lot for the hint. Definitely gonna use it in a future.
