### ISSUE TITLE
Cannot define packet size for mpegts stream. 

### ISSUE THREAD

**Issue by Lighty0410** [angelcam/rust-ac-ffmpeg#28]
Hey everyone ! What i'm trying to do is to define packet size for mpegts muxer. However, it seems like i'm doing something wrong. 
The way i define the muxer - `let mut muxer_builder = Muxer::builder().set_option("packetsize", 1316)` .
 
I also tried to set it directly to the muxer - 
```
let mut muxer = muxer_builder.build(io, output_format).unwrap();
muxer.set_option("packetsize", 1316);
```

However, it seems like no matter what i do the option doesn't apply at all. Because in a custom io-callback the buffer size exceeds the value defined in the option.
For example: 
```
mpeg-ts buf_size: 3840
mpeg-ts buf_size: 376
mpeg-ts buf_size: 2068
mpeg-ts buf_size: 4096
mpeg-ts buf_size: 792
mpeg-ts buf_size: 4096
mpeg-ts buf_size: 4096
mpeg-ts buf_size: 2524
mpeg-ts buf_size: 376
```
Weirdly enough this option works for RTP muxer for example. But i'm not able to find any `packetsize` options except for `AVFormatContext packetsize` and `mpegts demuxer ts_packetsize`. 
  
Any suggestions are really appreciated !   
P.S: as far as i understand each mpeg-ts packet size is 188 bytes - https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/mpegts.h#L29 up to 204 (if i understand correctly) . And then the muxer creates a buffer with multiple packets. If so is there a way to limit a number of packets in the output buffer ?

**Comment by operutka** [comment]
By briefly looking at the MPEG-TS muxer code, the "packetsize" option or the actual `AVFormatContext` field named `packet_size` have no effect there: http://ffmpeg.org/doxygen/4.1/mpegtsenc_8c_source.html

I'm not sure if what you're trying is possible. Check the MPEG-TS muxer options at the end of the [mpegtsenc.c](http://ffmpeg.org/doxygen/4.1/mpegtsenc_8c_source.html) or dive into the code of the muxer.

**Comment by Lighty0410** [comment]
> By briefly looking at the MPEG-TS muxer code, the "packetsize" option or the actual `AVFormatContext` field named `packet_size` have no effect there: http://ffmpeg.org/doxygen/4.1/mpegtsenc_8c_source.html
> 
> I'm not sure if what you're trying is possible. Check the MPEG-TS muxer options at the end of the [mpegtsenc.c](http://ffmpeg.org/doxygen/4.1/mpegtsenc_8c_source.html) or dive into the code of the muxer.

Thanks. Now i'm thinking about this way: is it useful to allow user to define his own buffer_size [https://github.com/angelcam/rust-ac-ffmpeg/blob/9384292641eeb4efc82e91a1f51dc708db3d8323/src/format/io.rs#L193](here) ? I can fork & implement this feature.

**Comment by operutka** [comment]
Changing the buffer size won't solve your problem. It'd only change the amount of data that the FFmpeg's AVIO can output at once but the resulting stream would be always the same. It won't affect the MPEG-TS packetization. If you need to post-process the muxed stream, you can do it easily by implementing your own `std::io::Write` stream and use it together with `ac_ffmpeg::format::io::IO`. You can take inspiration from the `ac_ffmpeg::format::io::MemWriter`.

If you just need a way to determine packet boundaries easily, you can flush the muxer after every packet. It'll flush any buffered data all the way to your `Write` stream. The mpegts muxers allows flushing at any time.

**Comment by Lighty0410** [comment]
> Changing the buffer size won't solve your problem. It'd only change the amount of data that the FFmpeg's AVIO can output at once but the resulting stream would be always the same. It won't affect the MPEG-TS packetization. If you need to post-process the muxed stream, you can do it easily by implementing your own `std::io::Write` stream and use it together with `ac_ffmpeg::format::io::IO`. You can take inspiration from the `ac_ffmpeg::format::io::MemWriter`.
> 
> If you just need a way to determine packet boundaries easily, you can flush the muxer after every packet. It'll flush any buffered data all the way to your `Write` stream. The mpegts muxers allows flushing at any time.

Got it, thank you! The last question then. Is there a way to use ffmpeg's native UDP outputs (multicast for example - _ffmpeg -i vid.ts -c copy -f mpegts  'udp://239.0.0.1:1234?ttl=13'_ ) ? Because as far as i see we need to define an IO by ourselves. But what about native solutions ? 

Thanks in advance!

**Comment by Lighty0410** [comment]
Oh, i tested it. And what's interesting. Setting packet size to 1316 (just an example value)  [here](https://github.com/angelcam/rust-ac-ffmpeg/blob/9384292641eeb4efc82e91a1f51dc708db3d8323/src/format/io.rs#L193) does in fact solve my issue ! Now the buffer length doesn't exceed 1316. 

Probably i didn't explain my issue correctly, excuse me. 
I don't want to change an mpeg-ts packet size itself. But i rather want to set a certain limit for the output buffer.

**Comment by operutka** [comment]
I see. So what's wrong with my original suggestion then? You can simply take 1316 bytes long chunks from the output stream. Instead of using `MemWriter` (or other `Write` streams), you can implement your own. Something like:
```rust
struct MyWriter {
    ...
    buffer: ByteMut,
    ...
}

impl Write for MyWriter {
    fn write(&mut self, buffer: &[u8]) -> Result<usize, io::Error> {
        self.buffer.extend_from_slice(buffer);

        while self.buffer.len() >= 1316 {
            let chunk = self.buffer.split_to(1316);

            // TODO: do something with the chunk
        }

        Ok(buffer.len())
    }

    fn flush(&mut self) -> Result<(), io::Error> {
        ...
    }
}
```

**Comment by operutka** [comment]
> Is there a way to use ffmpeg's native UDP outputs (multicast for example - ffmpeg -i vid.ts -c copy -f mpegts 'udp://239.0.0.1:1234?ttl=13' ) ?

No. Unfortunately, there is currently no way to use FFmpeg's own IO right now. But it should be relatively simple to implement your own UDP sender/receiver. If I'm not mistaken, FFmpeg's own UDP IO simply pipes the data into a UDP socket. There is no extra application protocol.

**Comment by Lighty0410** [comment]
> I see. So what's wrong with my original suggestion then? You can simply take 1316 bytes long chunks from the output stream. Instead of using `MemWriter` (or other `Write` streams), you can implement your own. Something like:
> 
> ```rust
> struct MyWriter {
>     ...
>     buffer: ByteMut,
>     ...
> }
> 
> impl Write for MyWriter {
>     fn write(&mut self, buffer: &[u8]) -> Result<usize, io::Error> {
>         self.buffer.extend_from_slice(buffer);
> 
>         while self.buffer.len() >= 1316 {
>             let chunk = self.buffer.split_to(1316);
> 
>             // TODO: do something with the chunk
>         }
> 
>         Ok(buffer.len())
>     }
> 
>     fn flush(&mut self) -> Result<(), io::Error> {
>         ...
>     }
> }
> ```

I did like exactly this before. At this point the problem is there's no guarantee that 1316 bytes == 7 packets 188 bytes each. It might be, let's stay 6 full + 1 incomplete packet. And, for example, when multicasting, a client application may or may not understand whether it should wait for another datagram or just drop the incomplete packet.
The reason why i cannot split a buffer that easily is the buffer size in the callback isn't always a multiple of 188. 
But when i set buffer size to 1316 i always get correct complete packets and the buffer size doesn't exceed a certain limit. 

Hope it makes sense. 
Btw, does it even make sense to create a PR here (since i already implemented custom buf size feature) ?

**Comment by operutka** [comment]
I ensure you that the code snippet I posted here behaves exactly as if you changed the buffer size to 1316. The output of the IO is a data stream. It really doesn't matter how big the buffer is. If you study the example more carefully, you'll see that it always consumes multiples of 1316 from the internal buffer and the remaining part will get reused on the next call of the write method.

For example let's say that the write method will get called with a buffer that contains 2732 bytes. All the contents of the buffer will be copied to `self.buffer`, the while loop will make 2 iterations consuming exactly 2632 bytes from the internal buffer. The remaining 100 bytes will stay in the internal buffer until the next call of the write method. Now let's say that the next call of the write method will be with a buffer containing 1216 bytes. Those 1216 bytes will be appended to the internal buffer, so the internal buffer will contain 1316 bytes in total (100 bytes from the previous call + 1216 bytes from the current one). The while loop will make one iteration consuming 1316 bytes. After the second call, the internal buffer will be empty.

**Comment by Lighty0410** [comment]
> I ensure you that the code snippet I posted here behaves exactly as if you changed the buffer size to 1316. The output of the IO is a data stream. It really doesn't matter how big the buffer is. If you study the example more carefully, you'll see that it always consumes multiples of 1316 from the internal buffer and the remaining part will get reused on the next call of the write method.
> 
> For example let's say that the write method will get called with a buffer that contains 2732 bytes. All the contents of the buffer will be copied to `self.buffer`, the while loop will make 2 iterations consuming exactly 2632 bytes from the internal buffer. The remaining 100 bytes will stay in the internal buffer until the next call of the write method. Now let's say that the next call of the write method will be with a buffer containing 1216 bytes. Those 1216 bytes will be appended to the internal buffer, so the internal buffer will contain 1316 bytes in total (100 bytes from the previous call + 1216 bytes from the current one). The while loop will make one iteration consuming 1316 bytes. After the second call, the internal buffer will be empty.

Got it. Thank you a lot ! I finally got the idea. Previously i implemented it a little bit differently (i put those 100 bytes in the socket too instead of filling the buffer, now i finally get my mistake). 
Yet again, thank you a lot! 

Btw, here's an example of a multicast application. And i hope it will be useful for someone in a future - 
https://gist.github.com/Lighty0410/2f2f2fa3ddb0542c57f9031cac5189ed

Closing an issue :)
