### ISSUE TITLE
Return error instead of panic

### ISSUE THREAD

**Issue by Hardebayho** [angelcam/rust-ac-ffmpeg#29]
https://github.com/angelcam/rust-ac-ffmpeg/blob/9384292641eeb4efc82e91a1f51dc708db3d8323/src/codec/bsf.rs#L48

I was reading through the source code (just for learning) and I encountered that line. I'm wondering if it is appropriate to panic if the bitstream filter could not be allocated. Isn't it better to return an error and have the user handle it instead? Since this is a library, I find it kind of weird that it is able to pull the rug from under an application without the application's consent.

If there's something I'm missing, please point it out so I can understand

**Comment by operutka** [comment]
That line is merely a sanity check. In fact, the application should never end up here. All error states should be already handled by:
```rust
if ret < 0 {
    return Err(Error::from_raw_error_code(ret));
}
```

**Comment by Hardebayho** [comment]
Oh, thank you
