### ISSUE TITLE
How to disable logging (set log level) ? 

### ISSUE THREAD

**Issue by Lighty0410** [angelcam/rust-ac-ffmpeg#37]
Hey everyone ! I'm trying to remux an mpegts stream to dash (mp4). And here's the problem i face. 
For some reasons the dash muxer loves to throw lots of logs which makes stdout really messy. Using ffmpeg in terminal i can set the log level. I tried using "loglevel" on the muxer builder, but nothing happened. 
Is there a way to do so using this crate ? 
Thanks in advance !

**Comment by operutka** [comment]
Hi @Lighty0410. You can use this function [set_log_callback](https://docs.rs/ac-ffmpeg/0.17.1/ac_ffmpeg/fn.set_log_callback.html) and simply drop the messages instead of logging them.

**Comment by Lighty0410** [comment]
> Hi @Lighty0410. You can use this function [set_log_callback](https://docs.rs/ac-ffmpeg/0.17.1/ac_ffmpeg/fn.set_log_callback.html) and simply drop the messages instead of logging them.

Thank you a lot ! Didn't see it. Closing the issue.
