### ISSUE TITLE
Can I use it to cut video?

### ISSUE THREAD

**Issue by hellostephanie2022** [angelcam/rust-ac-ffmpeg#58]
Hi. I've compared a lot of libraries, but I'm really impressed by the simplicity of the API you encapsulate. Good job! After reading the examples and source code, I still don’t know how to cut the video. Is it possible now?

This can look like this on the command line of `ffmpeg`: `ffmpeg -ss 30 -i input.wmv -c copy -t 10 output.wmv`, can you tell me how to do it?

**Comment by operutka** [comment]
Hi @hellostephanie2022 and thank you. To cut a video, you can simply take a certain range of packets/frames from the input (based on their timestamps) and write them to your output.

You don't have to transcode your video but keep in mind that your output should always start with a key-frame so, without transcoding, the cutting precision will be limited to GoP boundary. If you need to cut precisely at a certain point, you'll probably need to transcode your video (or at least some part of it).

If your media container supports seeking, you can use [the seek methods](https://docs.rs/ac-ffmpeg/0.18.1/ac_ffmpeg/format/demuxer/struct.Demuxer.html#method.seek_to_timestamp) to seek wherever you want within the container and start reading from there.

**Comment by operutka** [comment]
I hope I answered your question, so I'm closing the issue. Feel free to reopen it if needed.
