### ISSUE TITLE
Any parameter for hardware accelerate decode?

### ISSUE THREAD

**Issue by yukkodesu** [angelcam/rust-ac-ffmpeg#63]
as title, I've read decoding example, but still confused about enabling hwaccel

**Comment by operutka** [comment]
Hi @yukkodesu and sorry for the late reply. It's often hard to find some time for a pet project :) The hwaccel functionality of FFmpeg isn't exposed in this library. Patches are definitely welcome.

**Comment by yukkodesu** [comment]
thank you!
