### ISSUE TITLE
Compilation failed on Windows because there is no CC in the MSVC toolchain.

### ISSUE THREAD

**Issue by spritetong** [angelcam/rust-ac-ffmpeg#64]
So I make a patch for `get_ffmpeg_features()` in `build.rs`.

```rust
fn get_ffmpeg_features(all: bool) -> Vec<String> {
    // Patch for Windows.
    // Since there's no CC in the MSVC toolchain,
    // users should manually provide the environment variable "FFMPEG_FEATURES" instead.
    if let Ok(features) = env::var("FFMPEG_FEATURES") {
        return features
            .split(" \t,;")
            .filter_map(|s| {
                if !s.is_empty() {
                    Some(s.to_owned())
                } else {
                    None
                }
            })
            .collect();
    }

   /// ...
}
```

`FFMPEG_FEATURES` should be "channel_layout_v2" or an empty string according to `build/native-features.c`

**Comment by samuelkuz** [comment]
Hey Spritetong,
What steps did you have to do to get this compiling properly on windows? I've forked the repo and added this change, but I am not quite sure the necessary steps to get this compiling.

After adding this code to the start of the `get_ffmpeg_features` method, what should my environment variables `FFMPEG_FEATURES` contain?

**Comment by spritetong** [comment]
Hi samuelkuz，in addition to the `get_ffmpeg_features()` patch above，you should also set the environment value `FFMPEG_FEATURES` to `channel_layout_v2` (`channel layout` has been changed since ffmpeg 5.1+).

Command line:

```batch
set FFMPEG_FEATURES=channel_layout_v2
cargo build
```

`FFMPEG_FEATURES` can also be set in the `[env]` section of `.cargo/config.toml`.

**Comment by Tnze** [comment]
I think we need this patch to be merged

**Comment by operutka** [comment]
Hi everyone! Thank you for bringing this up. However, I don't think that allowing to override the feature list using an environment variable is a good idea. This could easily become a maintenance hell for projects using this library.

I've redesigned the build script a bit and added two helper crates as build dependencies for FFmpeg lookup and feature probing. I've also added vcpkg support on Windows. You can check the changes here: https://github.com/angelcam/rust-ac-ffmpeg/commit/eb8e8a64e46339c44ad306085aa5a814c14aec72

I've tested the Windows build with vcpkg and it seems to be working fine. You can try it yourself using:
```cmd
:: Install FFmpeg in your vcpkg directory
vcpkg install --triplet=x64-windows ffmpeg

:: Build the ac-ffmpeg lib
set VCPKG_ROOT=C:\path\to\vcpkg
set VCPKGRS_DYNAMIC=1
cargo build
```
