### ISSUE TITLE
RGB to YUV420p ?

### ISSUE THREAD

**Issue by void-dragon** [angelcam/rust-ac-ffmpeg#74]
hi, have a problem. I want to draw in RGB24 pixel format.
But libx264 expects YUV420p.
FFMPEG can do the conversion by itself but i did not found in the documentation how to actually do it with in this library.

**Comment by operutka** [comment]
Hi @void-dragon! As with the ffmpeg libraries themselves, you need to use the scaler to transform your frames from one pixel format to another: https://docs.rs/ac-ffmpeg/0.18.1/ac_ffmpeg/codec/video/scaler/struct.VideoFrameScaler.html

**Comment by void-dragon** [comment]
Thx, for removing the obvious splinter from my eye.

This works like a charm.
```rust
    let mut scaler = video::VideoFrameScaler::builder()
        .source_pixel_format(pixel_format_rgb)
        .source_width(width)
        .source_height(height)
        .target_pixel_format(pixel_format)
        .target_width(width)
        .target_height(height)
        .build()?;
    ...
    let conv_frame = scaler.scale(&frame.freeze())?;
    ...
```

**Comment by operutka** [comment]
Good! I'm closing the issue then.
