### ISSUE TITLE
Audio Frame sample data

### ISSUE THREAD

**Issue by Joseph-LeGrice** [angelcam/rust-ac-ffmpeg#8]
Hey, first off I'd like to say thank you for creating this library. The API is great, and I've got stuff rendering with it.

I'm just coming around to do audio stuff and noticed that there isn't support for exposing the sample data from audio frames. I have extended the API myself, using an interface similar to that you expose for VideoFrames (the Planes/Plane types). Would you be interested in looking at a pull request?

**Comment by operutka** [comment]
@Joseph-LeGrice perfect! I haven't had the time to do it myself. Feel free to create a pull request. I'll check it later this week.

**Comment by operutka** [comment]
The PR has been merged and a new version has been released. I'm closing this one.
